-- Generated by supabase/bootstrap/generate.py; do not hand-edit.

-- Empty application foundation: frozen 0001 + Alembic 0002 through 0011.

-- Historical source SHA-256 (LF normalized): 09b56a70fd8cac7aa920d25c4976be3101b3462d7c0487f1609faf95ab8e2caa

-- No Supabase deltas, data, passwords, runtime keys or migration stamps.

BEGIN;

SET LOCAL search_path = public, pg_catalog;

DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','S','f')) THEN
    RAISE EXCEPTION 'Bootstrap requires an empty public application schema';
  END IF;
END $$;

CREATE TABLE auth_security_subjects (
	subject_hash VARCHAR(64) NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (subject_hash)
);

CREATE TABLE users (
	id VARCHAR NOT NULL,
	email VARCHAR NOT NULL,
	hashed_password VARCHAR NOT NULL,
	role VARCHAR NOT NULL,
	subscription_status VARCHAR,
	display_name VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	google_sub VARCHAR,
	email_verified_at TIMESTAMP WITHOUT TIME ZONE,
	email_verification_required BOOLEAN DEFAULT true NOT NULL,
	email_verification_legacy_exempt BOOLEAN DEFAULT false NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE voucher_redemption_limits (
	subject_hash VARCHAR NOT NULL,
	minute_started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	minute_count INTEGER NOT NULL,
	hour_started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	hour_count INTEGER NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (subject_hash),
	CONSTRAINT ck_voucher_limit_counts CHECK (minute_count >= 0 AND hour_count >= 0)
);

CREATE TABLE webhook_events (
	id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	external_event_id VARCHAR NOT NULL,
	received_at TIMESTAMP WITHOUT TIME ZONE,
	processed_at TIMESTAMP WITHOUT TIME ZONE,
	status VARCHAR NOT NULL,
	PRIMARY KEY (id),
	UNIQUE (external_event_id)
);

CREATE TABLE audit_events (
	id VARCHAR NOT NULL,
	actor_user_id VARCHAR,
	event_type VARCHAR NOT NULL,
	resource_type VARCHAR NOT NULL,
	resource_id VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	metadata_json VARCHAR,
	PRIMARY KEY (id),
	FOREIGN KEY(actor_user_id) REFERENCES users (id)
);

CREATE TABLE auth_security_events (
	id VARCHAR NOT NULL,
	subject_hash VARCHAR(64) NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(subject_hash) REFERENCES auth_security_subjects (subject_hash)
);

CREATE TABLE client_devices (
	id VARCHAR NOT NULL,
	user_id VARCHAR,
	device_label VARCHAR,
	last_seen_at TIMESTAMP WITHOUT TIME ZONE,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE coaching_relationships (
	id SERIAL NOT NULL,
	coach_id VARCHAR NOT NULL,
	athlete_id VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	ended_at TIMESTAMP WITHOUT TIME ZONE,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(athlete_id) REFERENCES users (id),
	FOREIGN KEY(coach_id) REFERENCES users (id)
);

CREATE TABLE day_notes (
	id VARCHAR NOT NULL,
	owner_id VARCHAR NOT NULL,
	date VARCHAR NOT NULL,
	body VARCHAR NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(owner_id) REFERENCES users (id),
	CONSTRAINT uq_day_notes_owner_date UNIQUE (owner_id, date)
);

CREATE TABLE email_verification_tokens (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	token_hash VARCHAR(64) NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	consumed_at TIMESTAMP WITHOUT TIME ZONE,
	invalidated_at TIMESTAMP WITHOUT TIME ZONE,
	is_resend BOOLEAN NOT NULL,
	PRIMARY KEY (id),
	CONSTRAINT ck_email_token_hash_length CHECK (length(token_hash) = 64),
	CONSTRAINT ck_email_token_expiry CHECK (expires_at > created_at),
	FOREIGN KEY(user_id) REFERENCES users (id),
	UNIQUE (token_hash)
);

CREATE TABLE insight_cards (
	id VARCHAR NOT NULL,
	owner_user_id VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	config_json VARCHAR NOT NULL,
	layout_json VARCHAR NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(owner_user_id) REFERENCES users (id)
);

CREATE TABLE integration_connections (
	id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	external_account_id VARCHAR,
	status VARCHAR NOT NULL,
	scopes VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE invite_codes (
	id VARCHAR NOT NULL,
	coach_id VARCHAR NOT NULL,
	code_hash VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	used_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(coach_id) REFERENCES users (id)
);

CREATE TABLE mesocycles (
	id VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	color VARCHAR NOT NULL,
	"startDate" VARCHAR NOT NULL,
	"endDate" VARCHAR NOT NULL,
	owner_id VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(owner_id) REFERENCES users (id)
);

CREATE TABLE oauth_states (
	state_hash VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	return_to VARCHAR,
	PRIMARY KEY (state_hash),
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE sessions (
	id VARCHAR NOT NULL,
	user_id VARCHAR,
	jwt_id VARCHAR,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id)
);

CREATE TABLE sheet_publications (
	id VARCHAR NOT NULL,
	coach_id VARCHAR NOT NULL,
	spreadsheet_id VARCHAR NOT NULL,
	worksheet_name VARCHAR NOT NULL,
	export_profile VARCHAR NOT NULL,
	last_published_at TIMESTAMP WITHOUT TIME ZONE,
	status VARCHAR NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(coach_id) REFERENCES users (id)
);

CREATE TABLE vouchers (
	id VARCHAR NOT NULL,
	code_hash VARCHAR NOT NULL,
	code_prefix VARCHAR,
	plan_key VARCHAR NOT NULL,
	duration_days INTEGER NOT NULL,
	source VARCHAR NOT NULL,
	assigned_user_id VARCHAR,
	payment_reference VARCHAR,
	expires_at TIMESTAMP WITHOUT TIME ZONE,
	redeemed_at TIMESTAMP WITHOUT TIME ZONE,
	redeemed_by_user_id VARCHAR,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	created_by_user_id VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	notes VARCHAR,
	PRIMARY KEY (id),
	FOREIGN KEY(assigned_user_id) REFERENCES users (id),
	FOREIGN KEY(redeemed_by_user_id) REFERENCES users (id),
	FOREIGN KEY(created_by_user_id) REFERENCES users (id),
	CONSTRAINT ck_vouchers_duration_positive CHECK (duration_days > 0),
	UNIQUE (code_hash)
);

CREATE TABLE workspaces (
	id VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	owner_user_id VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(owner_user_id) REFERENCES users (id),
	CONSTRAINT uq_workspaces_owner_user_id UNIQUE (owner_user_id)
);

CREATE TABLE access_grants (
	id VARCHAR NOT NULL,
	workspace_id VARCHAR NOT NULL,
	plan_key VARCHAR NOT NULL,
	source VARCHAR NOT NULL,
	starts_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE,
	revoked_at TIMESTAMP WITHOUT TIME ZONE,
	created_by_user_id VARCHAR,
	reason VARCHAR,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(created_by_user_id) REFERENCES users (id),
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id)
);

CREATE TABLE billing_checkout_reservations (
	id VARCHAR NOT NULL,
	workspace_id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	request_id VARCHAR NOT NULL,
	plan_key VARCHAR NOT NULL,
	provider_checkout_session_id VARCHAR,
	provider_checkout_url VARCHAR,
	status VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id),
	CONSTRAINT uq_checkout_workspace_provider UNIQUE (workspace_id, provider),
	CONSTRAINT uq_checkout_provider_request UNIQUE (provider, request_id),
	CONSTRAINT ck_checkout_status CHECK (status IN ('CREATING', 'OPEN', 'COMPLETED', 'EXPIRED', 'CANCELED', 'FAILED'))
);

CREATE TABLE billing_customers (
	id VARCHAR NOT NULL,
	workspace_id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	provider_customer_id VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id),
	CONSTRAINT uq_billing_customers_provider_customer UNIQUE (provider, provider_customer_id),
	CONSTRAINT uq_billing_customers_workspace_provider UNIQUE (workspace_id, provider)
);

CREATE TABLE coaching_history_snapshots (
	relationship_id INTEGER NOT NULL,
	snapshot_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	snapshot_json VARCHAR NOT NULL,
	PRIMARY KEY (relationship_id),
	FOREIGN KEY(relationship_id) REFERENCES coaching_relationships (id)
);

CREATE TABLE integration_credentials (
	connection_id VARCHAR NOT NULL,
	credential_type VARCHAR NOT NULL,
	encrypted_payload VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE,
	rotated_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (connection_id, credential_type),
	FOREIGN KEY(connection_id) REFERENCES integration_connections (id)
);

CREATE TABLE integration_outbox (
	id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	connection_id VARCHAR,
	payload_json VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	retry_after TIMESTAMP WITHOUT TIME ZONE,
	attempt_count INTEGER,
	result VARCHAR,
	encrypted_payload VARCHAR,
	verification_token_id VARCHAR,
	PRIMARY KEY (id),
	FOREIGN KEY(connection_id) REFERENCES integration_connections (id),
	CONSTRAINT fk_outbox_verification_token FOREIGN KEY(verification_token_id) REFERENCES email_verification_tokens (id)
);

CREATE TABLE microcycles (
	id VARCHAR NOT NULL,
	"weekName" VARCHAR NOT NULL,
	focus VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	active BOOLEAN,
	owner_id VARCHAR,
	mesocycle_id VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(mesocycle_id) REFERENCES mesocycles (id),
	FOREIGN KEY(owner_id) REFERENCES users (id)
);

CREATE TABLE subscriptions (
	id VARCHAR NOT NULL,
	workspace_id VARCHAR NOT NULL,
	provider VARCHAR NOT NULL,
	provider_customer_id VARCHAR,
	provider_subscription_id VARCHAR NOT NULL,
	plan_key VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	current_period_start TIMESTAMP WITHOUT TIME ZONE,
	current_period_end TIMESTAMP WITHOUT TIME ZONE,
	cancel_at_period_end BOOLEAN NOT NULL,
	canceled_at TIMESTAMP WITHOUT TIME ZONE,
	ended_at TIMESTAMP WITHOUT TIME ZONE,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	provider_event_created_at TIMESTAMP WITHOUT TIME ZONE,
	provider_event_id VARCHAR,
	PRIMARY KEY (id),
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id),
	CONSTRAINT uq_subscriptions_provider_subscription UNIQUE (provider, provider_subscription_id),
	CONSTRAINT ck_subscriptions_status CHECK (status IN ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED', 'INCOMPLETE'))
);

CREATE TABLE sync_mutations (
	mutation_id VARCHAR NOT NULL,
	client_device_id VARCHAR NOT NULL,
	entity_type VARCHAR NOT NULL,
	entity_id VARCHAR NOT NULL,
	field_path VARCHAR NOT NULL,
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	applied_at TIMESTAMP WITHOUT TIME ZONE,
	result VARCHAR,
	PRIMARY KEY (mutation_id),
	FOREIGN KEY(client_device_id) REFERENCES client_devices (id)
);

CREATE TABLE workspace_members (
	id VARCHAR NOT NULL,
	workspace_id VARCHAR NOT NULL,
	user_id VARCHAR NOT NULL,
	role VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY(user_id) REFERENCES users (id),
	FOREIGN KEY(workspace_id) REFERENCES workspaces (id),
	CONSTRAINT ck_workspace_members_role CHECK (role IN ('OWNER', 'COACH', 'STAFF')),
	CONSTRAINT uq_workspace_members_workspace_user UNIQUE (workspace_id, user_id)
);

CREATE TABLE workouts (
	id VARCHAR NOT NULL,
	date VARCHAR NOT NULL,
	"dayLabel" VARCHAR NOT NULL,
	title VARCHAR NOT NULL,
	tonnage FLOAT,
	delta FLOAT,
	color VARCHAR NOT NULL,
	status VARCHAR NOT NULL,
	athlete_bw FLOAT,
	block_label VARCHAR,
	week_label VARCHAR,
	owner_id VARCHAR,
	microcycle_id VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(microcycle_id) REFERENCES microcycles (id),
	FOREIGN KEY(owner_id) REFERENCES users (id)
);

CREATE TABLE accessories (
	id VARCHAR NOT NULL,
	lexo_rank VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	"prescribedSets" VARCHAR NOT NULL,
	"targetReps" VARCHAR NOT NULL,
	"targetRpe" VARCHAR NOT NULL,
	weight VARCHAR,
	reps VARCHAR,
	"executedRpe" VARCHAR,
	status VARCHAR,
	workout_id VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(workout_id) REFERENCES workouts (id)
);

CREATE TABLE domain_events (
	id VARCHAR NOT NULL,
	workout_id VARCHAR NOT NULL,
	event_type VARCHAR NOT NULL,
	payload_json VARCHAR NOT NULL,
	created_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(workout_id) REFERENCES workouts (id)
);

CREATE TABLE exercises (
	id VARCHAR NOT NULL,
	lexo_rank VARCHAR NOT NULL,
	title VARCHAR NOT NULL,
	variation VARCHAR NOT NULL,
	tier VARCHAR,
	lift_category VARCHAR,
	movement_pattern VARCHAR,
	lift_note VARCHAR,
	tags_raw VARCHAR,
	top VARCHAR,
	vol VARCHAR,
	workout_id VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(workout_id) REFERENCES workouts (id)
);

CREATE TABLE workout_locks (
	workout_id VARCHAR NOT NULL,
	holder_user_id VARCHAR NOT NULL,
	mode VARCHAR NOT NULL,
	expires_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	version INTEGER,
	PRIMARY KEY (workout_id),
	FOREIGN KEY(holder_user_id) REFERENCES users (id),
	FOREIGN KEY(workout_id) REFERENCES workouts (id)
);

CREATE TABLE exercise_sets (
	id VARCHAR NOT NULL,
	lexo_rank VARCHAR NOT NULL,
	label VARCHAR NOT NULL,
	scope VARCHAR NOT NULL,
	"plannedWeight" FLOAT,
	"plannedReps" INTEGER,
	"plannedRpe" FLOAT,
	"dropPercent" FLOAT,
	"isAuto" BOOLEAN,
	actual FLOAT,
	reps INTEGER,
	"executedRpe" FLOAT,
	"isTop" BOOLEAN,
	intensity_type VARCHAR,
	note VARCHAR,
	velocity FLOAT,
	readiness INTEGER,
	hrv FLOAT,
	exercise_id VARCHAR,
	updated_at TIMESTAMP WITHOUT TIME ZONE,
	deleted_at TIMESTAMP WITHOUT TIME ZONE,
	PRIMARY KEY (id),
	FOREIGN KEY(exercise_id) REFERENCES exercises (id)
);

CREATE INDEX ix_access_grants_created_by_user_id ON access_grants (created_by_user_id);

CREATE INDEX ix_access_grants_workspace_id ON access_grants (workspace_id);

CREATE INDEX ix_accessories_id ON accessories (id);

CREATE INDEX ix_audit_events_id ON audit_events (id);

CREATE INDEX ix_auth_security_event_subject_time ON auth_security_events (subject_hash, created_at);

CREATE INDEX ix_checkout_workspace_id ON billing_checkout_reservations (workspace_id);

CREATE INDEX ix_billing_customers_provider_customer_id ON billing_customers (provider_customer_id);

CREATE INDEX ix_billing_customers_workspace_id ON billing_customers (workspace_id);

CREATE INDEX ix_client_devices_id ON client_devices (id);

CREATE UNIQUE INDEX uq_coaching_relationships_active_athlete ON coaching_relationships (athlete_id) WHERE ended_at IS NULL;

CREATE INDEX ix_day_notes_id ON day_notes (id);

CREATE INDEX ix_day_notes_owner_id ON day_notes (owner_id);

CREATE INDEX ix_domain_events_id ON domain_events (id);

CREATE INDEX ix_email_verification_tokens_expires_at ON email_verification_tokens (expires_at);

CREATE INDEX ix_email_verification_tokens_user_id ON email_verification_tokens (user_id);

CREATE UNIQUE INDEX uq_email_token_active_user ON email_verification_tokens (user_id) WHERE consumed_at IS NULL AND invalidated_at IS NULL;

CREATE INDEX ix_exercise_sets_id ON exercise_sets (id);

CREATE INDEX ix_exercises_id ON exercises (id);

CREATE INDEX ix_insight_cards_id ON insight_cards (id);

CREATE INDEX ix_insight_cards_owner_user_id ON insight_cards (owner_user_id);

CREATE INDEX ix_integration_connections_id ON integration_connections (id);

CREATE INDEX ix_integration_outbox_id ON integration_outbox (id);

CREATE INDEX ix_integration_outbox_verification_token_id ON integration_outbox (verification_token_id);

CREATE INDEX ix_invite_codes_id ON invite_codes (id);

CREATE INDEX ix_mesocycles_id ON mesocycles (id);

CREATE INDEX ix_microcycles_id ON microcycles (id);

CREATE INDEX ix_oauth_states_expires_at ON oauth_states (expires_at);

CREATE INDEX ix_oauth_states_provider ON oauth_states (provider);

CREATE INDEX ix_oauth_states_user_id ON oauth_states (user_id);

CREATE INDEX ix_sessions_id ON sessions (id);

CREATE UNIQUE INDEX ix_sessions_jwt_id ON sessions (jwt_id);

CREATE INDEX ix_sheet_publications_id ON sheet_publications (id);

CREATE INDEX ix_subscriptions_provider_customer_id ON subscriptions (provider_customer_id);

CREATE INDEX ix_subscriptions_provider_event_created_at ON subscriptions (provider_event_created_at);

CREATE INDEX ix_subscriptions_status ON subscriptions (status);

CREATE INDEX ix_subscriptions_workspace_id ON subscriptions (workspace_id);

CREATE INDEX ix_sync_mutations_mutation_id ON sync_mutations (mutation_id);

CREATE UNIQUE INDEX ix_users_email ON users (email);

CREATE INDEX ix_users_id ON users (id);

CREATE UNIQUE INDEX uq_users_google_sub ON users (google_sub);

CREATE INDEX ix_vouchers_assigned_user_id ON vouchers (assigned_user_id);

CREATE INDEX ix_vouchers_code_prefix ON vouchers (code_prefix);

CREATE INDEX ix_webhook_events_id ON webhook_events (id);

CREATE INDEX ix_workouts_id ON workouts (id);

CREATE INDEX ix_workspace_members_user_id ON workspace_members (user_id);

CREATE INDEX ix_workspace_members_workspace_id ON workspace_members (workspace_id);

CREATE INDEX ix_workspaces_owner_user_id ON workspaces (owner_user_id);

REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;

DO $$ DECLARE r text; BEGIN
  FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=r) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I',r);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I',r);
    END IF;
  END LOOP;
END $$;

COMMIT;
