"""Compile the frozen pre-Supabase Alembic DDL without loading backend runtime.

Only the empty-install path is supported. This never connects to a database,
imports backend.database, calls create_all(), or reads an environment file.
"""
from contextlib import contextmanager
import argparse
import hashlib
import importlib.util
from pathlib import Path

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DIALECT = postgresql.dialect()


class EmptyInstallDDL:
    def __init__(self):
        self.metadata = sa.MetaData()
        self.batch_table = None

    def get_bind(self):
        return self

    def get_table_names(self):
        return list(self.metadata.tables)

    def get_columns(self, name):
        return [{"name": c.name} for c in self.metadata.tables[name].columns]

    def get_indexes(self, name):
        return [{"name": i.name} for i in self.metadata.tables[name].indexes]

    def f(self, name):
        return name

    def create_table(self, name, *items, **kwargs):
        return sa.Table(name, self.metadata, *items, **kwargs)

    def create_index(self, name, table, columns, unique=False, **options):
        options.pop("sqlite_where", None)
        return sa.Index(name, *(self.metadata.tables[table].c[c] for c in columns),
                        unique=unique, **options)

    def add_column(self, *args):
        table, column = args if len(args) == 2 else (self.batch_table, args[0])
        self.metadata.tables[table].append_column(column)

    def alter_column(self, name, **options):
        # The only historical empty-install alteration is outbox connection nullable.
        assert self.batch_table == "integration_outbox" and name == "connection_id"
        assert options == {"existing_type": options["existing_type"], "nullable": True}
        self.metadata.tables[self.batch_table].c[name].nullable = True

    def create_foreign_key(self, name, target, local, remote):
        self.metadata.tables[self.batch_table].append_constraint(
            sa.ForeignKeyConstraint(local, [f"{target}.{c}" for c in remote], name=name))

    @contextmanager
    def batch_alter_table(self, table):
        assert self.batch_table is None
        self.batch_table = table
        parent = self

        class Batch:
            add_column = parent.add_column
            alter_column = parent.alter_column
            create_foreign_key = parent.create_foreign_key

            def create_index(self, name, columns):
                parent.create_index(name, table, columns)

        try:
            yield Batch()
        finally:
            self.batch_table = None

    def execute(self, statement):
        # These updates affect zero rows in the required empty foundation.
        assert str(statement) in (
            "UPDATE users SET email_verification_legacy_exempt = true",
            "UPDATE users SET email_verified_at = CURRENT_TIMESTAMP WHERE google_sub IS NOT NULL",
        ), f"Unhandled historical DML: {statement}"


def load(path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def historical_metadata():
    ddl = EmptyInstallDDL()
    frozen = ROOT / "backend/migrations/schema_0001.py"
    load(frozen).create_missing_tables(ddl, set())
    sources = [frozen]
    previous = "0001_current_schema"
    revisions = sorted((ROOT / "backend/migrations/versions").glob("*.py"))
    assert len(revisions) == 11
    assert revisions[0].name == "0001_current_schema.py"
    # 0001's actual empty-install DDL is the frozen snapshot above. Its legacy
    # validation/data-conversion paths are deliberately inapplicable to empty DBs.
    sources.append(revisions[0])
    for path in revisions[1:]:
        revision = load(path)
        assert revision.down_revision == previous
        revision.op = ddl
        revision.inspect = lambda bind: bind
        revision.upgrade()
        previous = revision.revision
        sources.append(path)
    assert previous == "0011_email_verification"
    assert len(ddl.metadata.tables) == 35
    return ddl.metadata, sources


def render():
    metadata, sources = historical_metadata()
    digest = hashlib.sha256(b"".join(p.read_bytes().replace(b"\r\n", b"\n") for p in sources)).hexdigest()
    parts = [
        "-- Generated by supabase/bootstrap/generate.py; do not hand-edit.",
        "-- Empty application foundation: frozen 0001 + Alembic 0002 through 0011.",
        f"-- Historical source SHA-256 (LF normalized): {digest}",
        "-- No Supabase deltas, data, passwords, runtime keys or migration stamps.",
        "BEGIN;",
        "SET LOCAL search_path = public, pg_catalog;",
        "DO $$ BEGIN\n"
        "  IF EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace\n"
        "    WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','S','f')) THEN\n"
        "    RAISE EXCEPTION 'Bootstrap requires an empty public application schema';\n"
        "  END IF;\nEND $$;",
    ]
    for table in metadata.sorted_tables:
        parts.append(str(CreateTable(table).compile(dialect=DIALECT)).strip() + ";")
    for table in sorted(metadata.tables.values(), key=lambda t: t.name):
        for index in sorted(table.indexes, key=lambda i: i.name):
            parts.append(str(CreateIndex(index).compile(dialect=DIALECT)).strip() + ";")
    # Supabase commonly installs default anon/authenticated grants. The baseline
    # must be private even before the RPC migrations; NOLOGIN groups don't exist yet.
    parts.extend([
        "REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;",
        "REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;",
        "DO $$ DECLARE r text; BEGIN\n"
        "  FOREACH r IN ARRAY ARRAY['anon','authenticated','service_role'] LOOP\n"
        "    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=r) THEN\n"
        "      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I',r);\n"
        "      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I',r);\n"
        "    END IF;\n  END LOOP;\nEND $$;",
        "COMMIT;",
    ])
    return "\n".join(line.rstrip() for line in "\n\n".join(parts).splitlines()) + "\n"


def main():
    if not __debug__:
        raise RuntimeError("Run without -O: bootstrap validation assertions must stay enabled")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = HERE / "application.sql"
    sql = render()
    if args.check:
        assert path.read_text(encoding="utf-8") == sql, "Bootstrap is stale; run generate.py"
        print("deterministic historical bootstrap: PASS")
    else:
        path.write_text(sql, encoding="utf-8", newline="\n")
        print(f"Wrote {path}")


if __name__ == "__main__":
    main()
